### ISSUE TITLE
Broken for Nova 2.12.0

### ISSUE THREAD

**Issue by Anticom** [iulianbilcu/nova-clickable-row#1]
I noticed the package is broken for nova 2.12.0, however I don't know in what version exactly the breaking change started.
It seems an extra element has been introduced somewhere inside the table cell holding the action buttons. Hence calling [parentElement](https://github.com/iulianbilcu/nova-clickable-row/blob/master/resources/js/asset.js#L44) only three times is no more sufficient.

So instead of doing
```js
const row = button.parentElement.parentElement.parentElement
```
I suggest something along the lines of
```js
const row = button.closest('tr')
```

Which [can be used](https://caniuse.com/#feat=element-closest) everywhere except in IE. And if you really want to support IE you could maybe introduce [this](https://github.com/jonathantneal/closest) polyfill.

**Comment by Anticom** [comment]
Please see [this](https://github.com/iulianbilcu/nova-clickable-row/pull/2) PR I've prepared to fix the issue.

**Comment by iulianbilcu** [comment]
Updated.
